### ISSUE TITLE
crear una aplicación móvil usando React Native CLI (no expo)

### ISSUE THREAD

**Issue by billygl** [AlanSaracho/lolocar-test#1]
Necesitamos una pantalla de bienvenida para nuestra aplicación móvil que estará hecha en react native. Esta es la pantalla a implementar:
![image](https://user-images.githubusercontent.com/442925/208963835-5cb8116a-1b9b-4d2e-ba0d-04f4a29c0e05.png)

Y considera una caja de texto que cuando se ingresa un nombre mayor a 3 caracteres muestra el mensaje de Hola con el nombre ingresado como se muestra en la imagen.
![image](https://user-images.githubusercontent.com/442925/208963773-5bd44b17-d972-44e6-ad8a-e468d5c6dc99.png)

considerar el diseño que viene por defecto al momento de generar el proyecto.

Como es urgente, esperamos que sea resuelto en el menor tiempo posible pero con la mayor calidad posible.

**Comment by AlanSaracho** [comment]
tiempo estimado: 5 a 10 minutos
