### ISSUE TITLE
comunicarse con un servicio REST

### ISSUE THREAD

**Issue by billygl** [AlanSaracho/lolocar-test#2]
Y considera una caja de texto que cuando se ingresa un nombre mayor a 3 caracteres muestra el mensaje de Hola con el nombre ingresado y su edad como se muestra en la imagen. La edad se obtiene del servicio web https://api.agify.io/?name=lolocar donde lolocar es el nombre ingresado y la edad no puede mostrarse como null
![image](https://user-images.githubusercontent.com/442925/208969446-536e2508-ce90-4a98-b4c2-a9d086355041.png)

Como es urgente, esperamos que sea resuelto en el menor tiempo posible pero con la mayor calidad posible.

**Comment by AlanSaracho** [comment]
tiempo estimado: 15 minutos
